/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UserInterface;

import Business.DatabaseUtil.DB4OUtil;
import Business.Doctor.Doctor;
import Business.EcoSystem;
import Business.PandemicCenter.PandemicCenter;
import UserInterface.SysAdmin.SysAdminWorkAreaJPanel;
import java.awt.CardLayout;
import java.awt.Color;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author shrikrishnajoisa
 */

public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */

    // set the default size of the main frame
     private EcoSystem system;
    public static DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    
    
    
    
    public MainJFrame() {
        initComponents();
        this.setSize(1920, 1080);
        this.setResizable(false);
         system = dB4OUtil.retrieveSystem();
         setSystemAdmin();
         //setAdminPage();
         
         
        
       
         
         
         //Creation of test data for all the tables
          Doctor doc = new Doctor("Raksha","Boston Public Hospital","Cardio","doctor1","doctor1","1111111111");
            system.getUserAccDir().addAccount(doc);
            system.getDoctorDir().addNewDoc(doc);
            
          PandemicCenter pCenter = new PandemicCenter("Raksha","Boston","1111111111","center1","center1");
              system.getUserAccDir().addAccount(pCenter);
            system.getPandemicCenterDir().addPandemicCenter(pCenter);
            
         
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        workArea = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        workArea.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(workArea, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 15, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(workArea, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }
    
 
    
    
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel workArea;
    // End of variables declaration//GEN-END:variables
   // Initial launch screen for the adminPage
    private void setAdminPage() {
         UserLogin wa=new UserLogin(workArea,system);
        workArea.add("UserLogin",wa);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
    }
    
    private void setSystemAdmin() {
        SysAdminWorkAreaJPanel wa=new SysAdminWorkAreaJPanel(workArea,system);
        workArea.add("UserLogins",wa);
        CardLayout layout = (CardLayout) workArea.getLayout();
        layout.next(workArea);
    }
  

}
