/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.Doctor;

import Business.BloodBank.BloodWork;
import Business.BloodBank.BloodWorkDirectory;
import Business.Doctor.Doctor;
import Business.EcoSystem;
import Business.UserAcc.UserAcc;
import Business.WorkQueue.Req_Blood;
import Business.WorkQueue.Req_BloodDir;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author shrikrishnajoisa
 */
public class RequestBlood extends javax.swing.JPanel {

    /**
     * Creates new form RequestBloodFrame
     */
    private UserAcc userAcc;
    private EcoSystem system;
    private JPanel container;

    public RequestBlood(JPanel userProcessContainer, EcoSystem ecosystem, UserAcc userAcc) {
        initComponents();
        this.system = ecosystem;
        this.container = userProcessContainer;
        this.userAcc = userAcc;
        displayTable();
        BloodWorkDirectory bloowWorkDir = ecosystem.getBloodBankDir();
        Doctor doc = (Doctor) (userAcc);
        firstNameTxt.setText(doc.getFirstName());

        ArrayList<BloodWork> bloodWorkList = bloowWorkDir.getBloodWorkList();
        int l = bloodWorkList.size();
        for (int i = 0; i < l; i++) {
            BloodWork bloodWork = bloodWorkList.get(i);
            bloodbank.addItem(bloodWork.getUserNames());

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        request = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        units = new javax.swing.JPanel();
        requestButtonButton = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        firstNameTxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        unit = new javax.swing.JTextField();
        bloodGroup = new javax.swing.JComboBox<>();
        bloodbank = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(250, 249, 251));
        setPreferredSize(new java.awt.Dimension(1920, 1080));

        request.setBackground(new java.awt.Color(250, 249, 251));
        request.setPreferredSize(new java.awt.Dimension(1920, 750));
        request.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SF Pro Display", 1, 24)); // NOI18N
        jLabel1.setText("Request Blood");
        request.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 31, -1, -1));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "User ID", "Password", "Phone Number"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable3);

        jPanel8.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 630));

        request.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 580, 630));

        units.setBackground(new java.awt.Color(255, 255, 255));
        units.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        requestButtonButton.setBackground(new java.awt.Color(10, 132, 255));
        requestButtonButton.setFont(new java.awt.Font("SF Pro Text", 0, 14)); // NOI18N
        requestButtonButton.setForeground(new java.awt.Color(255, 255, 255));
        requestButtonButton.setText("Request Blood");
        requestButtonButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestButtonButtonActionPerformed(evt);
            }
        });
        units.add(requestButtonButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 580, 200, 39));

        cancel.setBackground(new java.awt.Color(255, 55, 95));
        cancel.setFont(new java.awt.Font("SF Pro Text", 1, 14)); // NOI18N
        cancel.setForeground(new java.awt.Color(255, 255, 255));
        cancel.setText("Cancel Request");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        units.add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 580, 190, 39));

        jLabel2.setFont(new java.awt.Font("SF Pro Display", 1, 36)); // NOI18N
        jLabel2.setText("Enter Details");
        units.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 300, 50));

        jLabel7.setFont(new java.awt.Font("SF Pro Text", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(73, 84, 90));
        jLabel7.setText("Blood Group");
        units.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 220, -1));

        firstNameTxt.setFont(new java.awt.Font("SF Pro Text", 0, 14)); // NOI18N
        units.add(firstNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 420, 40));

        jLabel8.setFont(new java.awt.Font("SF Pro Text", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(73, 84, 90));
        jLabel8.setText("Doctor Name");
        units.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 220, -1));

        jLabel10.setFont(new java.awt.Font("SF Pro Text", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(73, 84, 90));
        jLabel10.setText("Center");
        units.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 220, -1));

        jLabel11.setFont(new java.awt.Font("SF Pro Text", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(73, 84, 90));
        jLabel11.setText("Units (oz)");
        units.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 220, -1));

        unit.setFont(new java.awt.Font("SF Pro Text", 0, 14)); // NOI18N
        unit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unitActionPerformed(evt);
            }
        });
        unit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                unitKeyPressed(evt);
            }
        });
        units.add(unit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 420, 40));

        bloodGroup.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A-", "B+", "B-", "O+", "O-", "AB+", "AB-" }));
        bloodGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bloodGroupActionPerformed(evt);
            }
        });
        units.add(bloodGroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 420, 40));

        units.add(bloodbank, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 420, 40));

        request.add(units, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 90, 470, 630));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(request, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(request, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable3MouseClicked

    private void requestButtonButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestButtonButtonActionPerformed
        // TODO add your handling code here:
        addBloodReq();


    }//GEN-LAST:event_requestButtonButtonActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:

        deleteBloodReq();
    }//GEN-LAST:event_cancelActionPerformed

    private void bloodGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bloodGroupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bloodGroupActionPerformed

    private void unitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unitActionPerformed

    private void unitKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_unitKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            unit.setEditable(false);
            JOptionPane.showMessageDialog(null, "enter number");
        } else {
            unit.setEditable(true);
        }
    }//GEN-LAST:event_unitKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> bloodGroup;
    private javax.swing.JComboBox<String> bloodbank;
    private javax.swing.JButton cancel;
    private javax.swing.JTextField firstNameTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable3;
    private javax.swing.JPanel request;
    private javax.swing.JButton requestButtonButton;
    private javax.swing.JTextField unit;
    private javax.swing.JPanel units;
    // End of variables declaration//GEN-END:variables

    private void displayTable() {
        // throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        {
            Req_BloodDir reBloodDir = system.getReqBloodDir();
            ArrayList<Req_Blood> reqBloodList = reBloodDir.getBloodReqDir();
            int l = reqBloodList.size();
            for (int i = 0; i < l; i++) {
                Req_Blood reqBlood = reqBloodList.get(i);
                if (userAcc.getUserName().matches(reqBlood.getDoctorId())) {
                    DefaultTableModel table = (DefaultTableModel) jTable3.getModel();
                    String s1 = String.valueOf(reqBlood.getId());
                    String s[] = {s1, reqBlood.getBloodBankName(), reqBlood.getStatus(), reqBlood.getBloodType(), Integer.toString(reqBlood.getUnits())};
                    table.addRow(s);
                }
            }

        }

    }

    private void addBloodReq() {
        // throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody

        if (unit.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "please enter all mandatory fields");
            return;
        }

        Req_Blood reqBlood = new Req_Blood();
        int z = 1 + (int) (Math.random() * 100);
        reqBlood.setId(z);
        reqBlood.setFirstName(firstNameTxt.getText());
        reqBlood.setBloodType(bloodGroup.getSelectedItem().toString());
        reqBlood.setBloodBankName(bloodbank.getSelectedItem().toString());
        reqBlood.setUnits(Integer.parseInt(unit.getText()));
        reqBlood.setStatus("In Progress");
        Req_BloodDir reqBloodDir = system.getReqBloodDir();
        Doctor doc = (Doctor) (userAcc);
        reqBlood.setDoctorId(userAcc.getUserName());
        reqBloodDir.addUserReq(reqBlood);

        JOptionPane.showMessageDialog(null, "Blood Unit Requested Successfully!!");
        jTable3.setModel(new DefaultTableModel(null, new String[]{"ID", "Center", "Status", "Blood Type", "Units requested"}));
        displayTable();

    }

    private void deleteBloodReq() {
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        DefaultTableModel table = (DefaultTableModel) jTable3.getModel();
        int selectedRow = jTable3.getSelectedRow();
        if (selectedRow >= 0) {
            int sRow = Integer.parseInt(table.getValueAt(selectedRow, 0).toString());
            //System.out.println("id"+s);
            Req_BloodDir reBloodDir = system.getReqBloodDir();
            ArrayList<Req_Blood> reBloodList = reBloodDir.getBloodReqDir();
            int l = reBloodList.size();

            for (int i = 0; i < l; i++) {
                Req_Blood reqBlood = reBloodList.get(i);
                if (sRow == reqBlood.getId()/*&&o.getStatus().matches("Deliver Man Assigned")*/) {
                    if (reqBlood.getStatus().matches("In Progress")) {
                        reqBlood.setStatus("Cancelled");
                    } else {
                        JOptionPane.showMessageDialog(null, "Wrong Move!!");
                    }
                }
            }
            jTable3.setModel(new DefaultTableModel(null, new String[]{"ID", "Center", "Status", "Blood Type", "Units requested"}));
            displayTable();
        } else {
            JOptionPane.showMessageDialog(null, "Select a Row!!");
        }

    }
}
