/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.user;

import Business.EcoSystem;
import Business.UserAcc.UserAcc;
import Business.WorkQueue.Req_Emergency;
import Business.WorkQueue.Req_EmergencyDir;
import Business.userR.User;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author shrikrishnajoisa
 */
public class EmergencyReport extends javax.swing.JPanel {

    /**
     * Creates new form EmergencyReport
     */
    JPanel container;
    EcoSystem system;
   UserAcc userAcc;
    public EmergencyReport(JPanel container,EcoSystem system,UserAcc userAcc) {
        initComponents();
         this.container=container;
        this.system=system;
        this.userAcc=userAcc;
        User a=(User)userAcc;
        firstNameField.setText(a.getFirstName());
        lastNameField.setText(a.getLastName());
        displayTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmergency = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        bookButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        firstNameLabel = new javax.swing.JLabel();
        lastNameField = new javax.swing.JTextField();
        lastNameLabel = new javax.swing.JLabel();
        firstNameField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        emergencyBox = new javax.swing.JComboBox<>();
        lastNameLabel1 = new javax.swing.JLabel();
        locationField = new javax.swing.JTextField();

        setBackground(new java.awt.Color(250, 249, 251));
        setPreferredSize(new java.awt.Dimension(1160, 750));

        jPanel1.setBackground(new java.awt.Color(250, 249, 251));
        jPanel1.setPreferredSize(new java.awt.Dimension(1160, 750));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SF Pro Display", 1, 24)); // NOI18N
        jLabel1.setText("Report Emergency");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 31, -1, -1));

        tblEmergency.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblEmergency);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 580, 630));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bookButton.setBackground(new java.awt.Color(10, 132, 255));
        bookButton.setFont(new java.awt.Font("SF Pro Text", 0, 14)); // NOI18N
        bookButton.setForeground(new java.awt.Color(255, 255, 255));
        bookButton.setText("Report");
        bookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookButtonActionPerformed(evt);
            }
        });
        jPanel7.add(bookButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 580, 210, 39));

        cancelButton.setBackground(new java.awt.Color(255, 55, 95));
        cancelButton.setFont(new java.awt.Font("SF Pro Text", 1, 14)); // NOI18N
        cancelButton.setForeground(new java.awt.Color(255, 255, 255));
        cancelButton.setText("Close");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        jPanel7.add(cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 580, 200, 39));

        jLabel2.setFont(new java.awt.Font("SF Pro Display", 1, 24)); // NOI18N
        jLabel2.setText("Enter Details");
        jPanel7.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 300, 50));

        firstNameLabel.setFont(new java.awt.Font("SF Pro Text", 0, 18)); // NOI18N
        firstNameLabel.setForeground(new java.awt.Color(73, 84, 90));
        firstNameLabel.setText("First Name");
        jPanel7.add(firstNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 220, -1));

        lastNameField.setFont(new java.awt.Font("SF Pro Text", 0, 14)); // NOI18N
        jPanel7.add(lastNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 420, 40));

        lastNameLabel.setFont(new java.awt.Font("SF Pro Text", 0, 18)); // NOI18N
        lastNameLabel.setForeground(new java.awt.Color(73, 84, 90));
        lastNameLabel.setText("Last Name");
        jPanel7.add(lastNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 220, -1));

        firstNameField.setFont(new java.awt.Font("SF Pro Text", 0, 14)); // NOI18N
        jPanel7.add(firstNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 420, 40));

        jLabel9.setFont(new java.awt.Font("SF Pro Text", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(73, 84, 90));
        jLabel9.setText("Emergency");
        jPanel7.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 220, -1));

        emergencyBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ambulance", "Fire", "Police" }));
        jPanel7.add(emergencyBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 420, 40));

        lastNameLabel1.setFont(new java.awt.Font("SF Pro Text", 0, 18)); // NOI18N
        lastNameLabel1.setForeground(new java.awt.Color(73, 84, 90));
        lastNameLabel1.setText("Location");
        jPanel7.add(lastNameLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 220, -1));

        locationField.setFont(new java.awt.Font("SF Pro Text", 0, 14)); // NOI18N
        jPanel7.add(locationField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 420, 40));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 90, 470, 630));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 822, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookButtonActionPerformed
        // TODO add your handling code here:
       reportEmergency();

        
    }//GEN-LAST:event_bookButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        
        cancelEmergency();
        
        
    }//GEN-LAST:event_cancelButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bookButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JComboBox<String> emergencyBox;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lastNameField;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JLabel lastNameLabel1;
    private javax.swing.JTextField locationField;
    private javax.swing.JTable tblEmergency;
    // End of variables declaration//GEN-END:variables

    private void displayTable() {
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
     Req_EmergencyDir red=system.getEmergencyReqDir();
        ArrayList<Req_Emergency> ol=red.getEmergencyUserList();
        int u=ol.size();
        for(int i=0;i<u;i++)
        {
            Req_Emergency o=ol.get(i);
            if(userAcc.getUserName().matches(o.getUserId()))
            {
                DefaultTableModel t2 = (DefaultTableModel) tblEmergency.getModel();
                String s1=String.valueOf(o.getId());    
                String s[]={s1,o.getEmergency(),o.getLocation(),o.getStatus(),o.getResponse()};
                t2.addRow(s);
            }
        }
    
    
    
    
    }

    private void reportEmergency() {
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
     if(!locationField.getText().isEmpty())
        {
            Req_Emergency re=new Req_Emergency();
        User a=(User)userAcc;
        int x = 1 + (int) (Math.random() * 100);
        re.setId(x);
        re.setName(a.getFirstName());
        re.setUserId(a.getUserId());
        re.setEmergency(emergencyBox.getSelectedItem().toString());
        re.setLocation(locationField.getText());
        re.setStatus("In Progress");
        re.setResponse("No Response");
            Req_EmergencyDir red=system.getEmergencyReqDir();
        red.addEmergencyUser(re);
        tblEmergency.setModel(new DefaultTableModel(null,new String[]{"ID","Emergency","Location","Status","Response"}));
        displayTable();
                    JOptionPane.showMessageDialog(null, "Reported Emergency Successfully!!!");
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Please Enter the location for Emergency Services!");
        }}

    private void cancelEmergency() {
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    DefaultTableModel t2 = (DefaultTableModel) tblEmergency.getModel();
        int selectedRow=tblEmergency.getSelectedRow();
        if(selectedRow>=0)
        {
        int s=Integer.parseInt(t2.getValueAt(selectedRow, 0).toString());
        Req_EmergencyDir red= system.getEmergencyReqDir();
        ArrayList<Req_Emergency> ol=red.getEmergencyUserList();
        int u=ol.size();
        for(int i=0;i<u;i++)
        {
            Req_Emergency o=ol.get(i);
            if(s==o.getId())
            {
                if(o.getStatus().matches("In Progress"))
                {
                o.setStatus("Closed");
                JOptionPane.showMessageDialog(null, "Case Closed");
              
            }
                else if(o.getStatus().matches("Closed")){
                    JOptionPane.showMessageDialog(null, "Your Emergency Case is Closed successfully!!");
                }   
            else
            {
                JOptionPane.showMessageDialog(null, "Reported as false Alarm!!");
            }
            }
            
        }
        tblEmergency.setModel(new DefaultTableModel(null,new String[]{"ID","Emergency","Location","Status","Response"}));
       displayTable();
        }
        else
        {
       JOptionPane.showMessageDialog(null, "Select A Row!!");

        }
    
    
    
    
    }
}
