/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.BloodBank;

import Business.BloodBank.BloodWork;
import Business.BloodBank.BloodWorkDirectory;
import Business.EcoSystem;
import Business.UserAcc.UserAcc;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author shrikrishnajoisa
 */
public class BloodStock extends javax.swing.JPanel {

    /**
     * Creates new form BloodStock
     */
    private UserAcc userAcc;
    private EcoSystem system;
    private JPanel container;

    public BloodStock(JPanel userProcessContainer, EcoSystem system, UserAcc userAcc) {
        initComponents();
        this.system = system;
        this.container = userProcessContainer;
        this.userAcc = userAcc;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtAp = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtBp = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtbm = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtABp = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtAm = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtOm = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtOp = new javax.swing.JTextField();
        txtABm = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();

        setBackground(new java.awt.Color(250, 249, 251));
        setPreferredSize(new java.awt.Dimension(1160, 750));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(250, 249, 251));
        jPanel1.setPreferredSize(new java.awt.Dimension(1160, 750));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("SF Pro", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(231, 97, 93));
        jLabel2.setText("Blood Stock");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("SF Pro Text", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(73, 84, 90));
        jLabel3.setText("Update the blood stock here and manage them");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, -1, -1));

        jLabel4.setFont(new java.awt.Font("SF Pro Text", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(73, 84, 90));
        jLabel4.setText("A+");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, -1, -1));

        txtAp.setBackground(new java.awt.Color(248, 248, 249));
        txtAp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApActionPerformed(evt);
            }
        });
        txtAp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtApKeyPressed(evt);
            }
        });
        jPanel2.add(txtAp, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 271, 48));

        jLabel5.setFont(new java.awt.Font("SF Pro Text", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(73, 84, 90));
        jLabel5.setText("B+");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, -1, -1));

        txtBp.setBackground(new java.awt.Color(248, 248, 249));
        txtBp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBpKeyPressed(evt);
            }
        });
        jPanel2.add(txtBp, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 271, 48));

        jLabel6.setFont(new java.awt.Font("SF Pro Text", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(73, 84, 90));
        jLabel6.setText("B-");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, -1, -1));

        txtbm.setBackground(new java.awt.Color(248, 248, 249));
        txtbm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtbmKeyPressed(evt);
            }
        });
        jPanel2.add(txtbm, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 240, 271, 48));

        jLabel7.setFont(new java.awt.Font("SF Pro Text", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(73, 84, 90));
        jLabel7.setText("AB+");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 410, -1, -1));

        txtABp.setBackground(new java.awt.Color(248, 248, 249));
        txtABp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtABpKeyPressed(evt);
            }
        });
        jPanel2.add(txtABp, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 450, 271, 48));

        jLabel9.setFont(new java.awt.Font("SF Pro Text", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(73, 84, 90));
        jLabel9.setText("A-");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, -1, -1));

        txtAm.setBackground(new java.awt.Color(248, 248, 249));
        txtAm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAmKeyPressed(evt);
            }
        });
        jPanel2.add(txtAm, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, 271, 48));

        jLabel8.setFont(new java.awt.Font("SF Pro Text", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(73, 84, 90));
        jLabel8.setText("O-");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 310, -1, -1));

        txtOm.setBackground(new java.awt.Color(248, 248, 249));
        txtOm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtOmKeyPressed(evt);
            }
        });
        jPanel2.add(txtOm, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 350, 271, 48));

        jLabel10.setFont(new java.awt.Font("SF Pro Text", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(73, 84, 90));
        jLabel10.setText("O+");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, -1, -1));

        txtOp.setBackground(new java.awt.Color(248, 248, 249));
        txtOp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtOpKeyPressed(evt);
            }
        });
        jPanel2.add(txtOp, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, 271, 48));

        txtABm.setBackground(new java.awt.Color(248, 248, 249));
        txtABm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtABmKeyPressed(evt);
            }
        });
        jPanel2.add(txtABm, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 450, 271, 48));

        jLabel11.setFont(new java.awt.Font("SF Pro Text", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(73, 84, 90));
        jLabel11.setText("AB-");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 410, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 779, 528));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 636));

        btnAdd.setBackground(new java.awt.Color(235, 97, 91));
        btnAdd.setFont(new java.awt.Font("SF Pro Text", 1, 18)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("Add Stock");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(508, 654, 179, 56));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        updateStock();
        JOptionPane.showMessageDialog(null, "stock updated!!");
    }//GEN-LAST:event_btnAddActionPerformed

    private void txtApActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtApActionPerformed

    private void txtApKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            txtAp.setEditable(false);
            JOptionPane.showMessageDialog(null, "enter number");
        } else {
            txtAp.setEditable(true);
        }
    }//GEN-LAST:event_txtApKeyPressed

    private void txtAmKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAmKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            txtAm.setEditable(false);
            JOptionPane.showMessageDialog(null, "enter number");
        } else {
            txtAm.setEditable(true);
        }
    }//GEN-LAST:event_txtAmKeyPressed

    private void txtBpKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBpKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            txtBp.setEditable(false);
            JOptionPane.showMessageDialog(null, "enter number");
        } else {
            txtBp.setEditable(true);
        }
    }//GEN-LAST:event_txtBpKeyPressed

    private void txtbmKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbmKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            txtbm.setEditable(false);
            JOptionPane.showMessageDialog(null, "enter number");
        } else {
            txtbm.setEditable(true);
        }
    }//GEN-LAST:event_txtbmKeyPressed

    private void txtOpKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOpKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            txtOp.setEditable(false);
            JOptionPane.showMessageDialog(null, "enter number");
        } else {
            txtOp.setEditable(true);
        }
    }//GEN-LAST:event_txtOpKeyPressed

    private void txtOmKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOmKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            txtOm.setEditable(false);
            JOptionPane.showMessageDialog(null, "enter number");
        } else {
            txtOm.setEditable(true);
        }
    }//GEN-LAST:event_txtOmKeyPressed

    private void txtABpKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtABpKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            txtBp.setEditable(false);
            JOptionPane.showMessageDialog(null, "enter number");
        } else {
            txtBp.setEditable(true);
        }
    }//GEN-LAST:event_txtABpKeyPressed

    private void txtABmKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtABmKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            txtABm.setEditable(false);
            JOptionPane.showMessageDialog(null, "enter number");
        } else {
            txtABm.setEditable(true);
        }
    }//GEN-LAST:event_txtABmKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtABm;
    private javax.swing.JTextField txtABp;
    private javax.swing.JTextField txtAm;
    private javax.swing.JTextField txtAp;
    private javax.swing.JTextField txtBp;
    private javax.swing.JTextField txtOm;
    private javax.swing.JTextField txtOp;
    private javax.swing.JTextField txtbm;
    // End of variables declaration//GEN-END:variables

    private void updateStock() {
        // throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        if (txtAp.getText().isEmpty() || txtAm.getText().isEmpty() || txtBp.getText().isEmpty() || txtbm.getText().isEmpty() || txtOp.getText().isEmpty() || txtOm.getText().isEmpty() || txtABp.getText().isEmpty() || txtABm.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "please enter all mandatory fields");
            return;
        }
        BloodWorkDirectory bwd = system.getBloodBankDir();
        ArrayList<BloodWork> bw = bwd.getBloodWorkList();
        int s = bw.size();

        BloodWork b = (BloodWork) (userAcc);
        for (int i = 0; i < s; i++) {
            BloodWork o = bw.get(i);
            if (o.getUserNames().matches(b.getUserNames())) {

                Map<String, Integer> stock = new HashMap<String, Integer>();
                stock.put("A+", Integer.parseInt(txtAp.getText()));
                stock.put("A-", Integer.parseInt(txtAm.getText()));
                stock.put("B+", Integer.parseInt(txtBp.getText()));
                stock.put("B-", Integer.parseInt(txtbm.getText()));
                stock.put("O+", Integer.parseInt(txtOp.getText()));
                stock.put("O-", Integer.parseInt(txtOm.getText()));
                stock.put("AB+", Integer.parseInt(txtABp.getText()));
                stock.put("AB-", Integer.parseInt(txtABm.getText()));
                o.setLabMap(stock);
            }
        }

    }

}
