/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.BloodBank;

import Business.BloodBank.BloodWork;
import Business.EcoSystem;
import Business.UserAcc.UserAcc;
import Business.WorkQueue.Req_Blood;
import Business.WorkQueue.Req_BloodDir;
import Business.WorkQueue.SearchApp;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author shrikrishnajoisa
 */
public class DocRequest extends javax.swing.JPanel {

    /**
     * Creates new form DocRequest
     */
    private UserAcc userAcc;
    private EcoSystem system;
    private JPanel container;

    public DocRequest(JPanel userProcessContainer, EcoSystem system, UserAcc userAcc) {
        initComponents();
        this.system = system;
        this.container = userProcessContainer;
        this.userAcc = userAcc;
        displayTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        bookButton1 = new javax.swing.JButton();
        bookButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(250, 249, 251));
        setPreferredSize(new java.awt.Dimension(1160, 750));

        jPanel1.setBackground(new java.awt.Color(250, 249, 251));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Name", "Location", "Status", "Response"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 853, -1));

        bookButton1.setBackground(new java.awt.Color(10, 132, 255));
        bookButton1.setFont(new java.awt.Font("SF Pro Text", 0, 14)); // NOI18N
        bookButton1.setForeground(new java.awt.Color(255, 255, 255));
        bookButton1.setText("Process Request");
        bookButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(bookButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 590, 180, 50));

        bookButton.setBackground(new java.awt.Color(255, 69, 58));
        bookButton.setFont(new java.awt.Font("SF Pro Text", 0, 14)); // NOI18N
        bookButton.setForeground(new java.awt.Color(255, 255, 255));
        bookButton.setText("Cancel");
        bookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookButtonActionPerformed(evt);
            }
        });
        jPanel1.add(bookButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 590, 180, 50));

        jLabel1.setFont(new java.awt.Font("SF Pro Display", 1, 24)); // NOI18N
        jLabel1.setText("Process Request");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 31, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bookButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookButton1ActionPerformed
        // TODO add your handling code here:
        AcceptReq();
    }//GEN-LAST:event_bookButton1ActionPerformed

    private void bookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookButtonActionPerformed
        // TODO add your handling code here:
        rejectReq();
    }//GEN-LAST:event_bookButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bookButton;
    private javax.swing.JButton bookButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    private void displayTable() {
        // throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        Req_BloodDir rbd = system.getReqBloodDir();
        ArrayList<Req_Blood> ol = rbd.getBloodReqDir();
        int u = ol.size();

        for (int i = 0; i < u; i++) {
            Req_Blood o = ol.get(i);
            BloodWork bb = (BloodWork) (userAcc);

            if (o.getBloodBankName().matches(bb.getUserNames())) {
                DefaultTableModel t2 = (DefaultTableModel) jTable1.getModel();
                String s1 = String.valueOf(o.getId());
                String s[] = {s1, o.getFirstName(), o.getStatus(), o.getBloodType(), Integer.toString(o.getUnits())};
                t2.addRow(s);
            }
        }
    }

    private boolean Verify() {
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        DefaultTableModel t2 = (DefaultTableModel) jTable1.getModel();
        int selectedRow = jTable1.getSelectedRow();
        int s = Integer.parseInt(t2.getValueAt(selectedRow, 0).toString());

        Req_BloodDir rbd = system.getReqBloodDir();
        ArrayList<Req_Blood> ol = rbd.getBloodReqDir();

        int u = ol.size();
        boolean r = false;
        BloodWork bb = (BloodWork) (userAcc);
        for (int i = 0; i < u; i++) {
            Req_Blood o = ol.get(i);
            if (s == o.getId()) {

                String gj = o.getBloodType();
                int a = o.getUnits();

                Map<String, Integer> stock = bb.getLabMap();
                for (Map.Entry<String, Integer> set : stock.entrySet()) {

                    if (set.getKey().equals(gj)) {
                        if (set.getValue() > a) {

                            r = true;
                            break;
                        }
                    }
                }
            }
        }
        return r;
    }

    public void app() {
        Req_BloodDir rbd = system.getReqBloodDir();
        ArrayList<Req_Blood> ol = rbd.getBloodReqDir();

        int u = ol.size();
        BloodWork bb = (BloodWork) (userAcc);
        for (int i = 0; i < u; i++) {
            Req_Blood o = ol.get(i);
            String gj = o.getBloodType();
            int a = o.getUnits();

            Map<String, Integer> stock = bb.getLabMap();
            for (Map.Entry<String, Integer> set : stock.entrySet()) {

                if (set.getKey().equals(gj)) {
                    int a1 = set.getValue();
                    int b = a1 - a;
                    set.setValue(b);

                }
            }
        }
    }

    private void AcceptReq() {
        // throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        DefaultTableModel t2 = (DefaultTableModel) jTable1.getModel();
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow >= 0) {
            int s = Integer.parseInt(t2.getValueAt(selectedRow, 0).toString());

            Req_BloodDir rbd = system.getReqBloodDir();
            ArrayList<Req_Blood> ol = rbd.getBloodReqDir();

            int u = ol.size();
            BloodWork bb = (BloodWork) (userAcc);
            for (int i = 0; i < u; i++) {
                Req_Blood o = ol.get(i);
                if (s == o.getId()) {
                    if (o.getStatus().matches("In Progress")) {
                        boolean r = Verify();
                        if (r == false) {
                            o.setStatus("Cancelled");
                            JOptionPane.showMessageDialog(null, "Inadequate Inventory");

                        } else {
                            app();
                            o.setStatus("Approved");
                            JOptionPane.showMessageDialog(null, "Request Approved!!");

                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Wrong Move!!");

                    }

                }

            }
            jTable1.setModel(new DefaultTableModel(null, new String[]{"ID", "Name", "Status", "Blood Type", "Units requested"}));
            displayTable();
        } else {
            JOptionPane.showMessageDialog(null, "Select a Row!!");
        }
    }

    private void rejectReq() {
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
     DefaultTableModel  t2 = (DefaultTableModel) jTable1.getModel();
        int selectedRow=jTable1.getSelectedRow();
        if(selectedRow>=0)
        {
        int s=Integer.parseInt(t2.getValueAt(selectedRow, 0).toString());
        System.out.println("id"+s);
        Req_BloodDir rbd = system.getReqBloodDir();
            ArrayList<Req_Blood> ol = rbd.getBloodReqDir();

        int u=ol.size();
        BloodWork bb = (BloodWork) (userAcc);
        for(int i=0;i<u;i++)
        {
            Req_Blood o=ol.get(i);
            if(s==o.getId()/*&&o.getStatus().matches("Deliver Man Assigned")*/)
            {
                if(o.getStatus().matches("In Progress"))
                {
                    o.setStatus("Cancelled");
                }
                else
                {
                    JOptionPane.showMessageDialog(null,"Wrong Move!!");
                }
            }
        }
        jTable1.setModel(new DefaultTableModel(null,new String[]{"ID","Name","Status","Blood Type","Units requested"}));
        displayTable();
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Select a Row!!");
        }
    
    
    
    }
}
