/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.Fire;

import Business.EcoSystem;
import Business.EmergencyFire.Fire;
//import Business.EmergencyFire.Fire;
import Business.UserAcc.UserAcc;
import Business.WorkQueue.Req_Emergency;
import Business.WorkQueue.Req_EmergencyDir;
import UserInterface.SysAdmin.MapViewerTwo;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author shrikrishnajoisa
 */
public class FireDisplay extends javax.swing.JPanel {

   

    
     private UserAcc userAcc;
    private EcoSystem system;
    private JPanel container;
    String locationCordinate;
    /**
     * Creates new form FireDisplay
     */
    public FireDisplay(EcoSystem ecosystem, JPanel userProcessContainer, UserAcc userAcc) {
        this.system = ecosystem;
        this.container = userProcessContainer;
        this.userAcc = userAcc;
        initComponents();
        populate_table();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        respondButton = new javax.swing.JButton();
        closeCase = new javax.swing.JButton();
        falseAlarm = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        locationButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(250, 249, 251));
        setPreferredSize(new java.awt.Dimension(1160, 750));

        jPanel1.setBackground(new java.awt.Color(250, 249, 251));
        jPanel1.setPreferredSize(new java.awt.Dimension(1160, 750));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Name", "Location", "Status", "Response"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 853, -1));

        respondButton.setBackground(new java.awt.Color(10, 132, 255));
        respondButton.setFont(new java.awt.Font("SF Pro Text", 0, 14)); // NOI18N
        respondButton.setForeground(new java.awt.Color(255, 255, 255));
        respondButton.setText("Respond");
        respondButton.setBorder(null);
        respondButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                respondButtonActionPerformed(evt);
            }
        });
        jPanel1.add(respondButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 590, 180, 50));

        closeCase.setBackground(new java.awt.Color(255, 69, 58));
        closeCase.setFont(new java.awt.Font("SF Pro Text", 0, 14)); // NOI18N
        closeCase.setForeground(new java.awt.Color(255, 255, 255));
        closeCase.setText("Close Case");
        closeCase.setBorder(null);
        closeCase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeCaseActionPerformed(evt);
            }
        });
        jPanel1.add(closeCase, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 590, 180, 50));

        falseAlarm.setBackground(new java.awt.Color(255, 55, 95));
        falseAlarm.setFont(new java.awt.Font("SF Pro Text", 0, 14)); // NOI18N
        falseAlarm.setForeground(new java.awt.Color(255, 255, 255));
        falseAlarm.setText("False Alarm");
        falseAlarm.setBorder(null);
        falseAlarm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                falseAlarmActionPerformed(evt);
            }
        });
        jPanel1.add(falseAlarm, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 590, 180, 50));

        jLabel1.setFont(new java.awt.Font("SF Pro Display", 1, 24)); // NOI18N
        jLabel1.setText("Fire emergency details");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 31, -1, -1));

        locationButton.setBackground(new java.awt.Color(172, 142, 104));
        locationButton.setFont(new java.awt.Font("SF Pro Text", 0, 14)); // NOI18N
        locationButton.setForeground(new java.awt.Color(255, 255, 255));
        locationButton.setText("View Location");
        locationButton.setBorder(null);
        locationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locationButtonActionPerformed(evt);
            }
        });
        jPanel1.add(locationButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 590, 180, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void falseAlarmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_falseAlarmActionPerformed
        // TODO add your handling code here:
        DefaultTableModel table = (DefaultTableModel) jTable1.getModel();
        int selectedRow=jTable1.getSelectedRow();
        if(selectedRow>=0)
        {
        int rowId = Integer.parseInt(table.getValueAt(selectedRow, 0).toString());
        
        Req_EmergencyDir reqEmergencyDir =system.getEmergencyReqDir();
        ArrayList<Req_Emergency> emergencies = reqEmergencyDir.getEmergencyUserList();
        Fire a=(Fire)userAcc;
        int size = emergencies.size();
        for(int i=0;i<size;i++)
        {
            Req_Emergency emergency = emergencies.get(i);
            if(rowId == emergency.getId())
            {
                locationCordinate = emergency.getLocation();
                if(emergency.getStatus().matches("Closed"))
                {
                    JOptionPane.showMessageDialog(null, "Emergency Closed");
                }
                else if(emergency.getStatus().matches("False Alarm"))
                {
                    JOptionPane.showMessageDialog(null, "Emergency is a false Alaram");
                }
                else if(emergency.getResponse().matches("No Response"))
                {
                    JOptionPane.showMessageDialog(null, "respond to emergency");
                }
                else
                {
                    emergency.setStatus("False Alarm");
                }
                
                

            }

        }
        jTable1.setModel(new DefaultTableModel(null,new String[]{"ID","Name","Emergency","Location","Status","Response"}));
        populate_table();
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Select A Row!!");
        }
    }//GEN-LAST:event_falseAlarmActionPerformed

    private void closeCaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeCaseActionPerformed
        // TODO add your handling code here:
        DefaultTableModel table = (DefaultTableModel) jTable1.getModel();
        int selectedRow=jTable1.getSelectedRow();
        if(selectedRow>=0)
        {
        int rowId = Integer.parseInt(table.getValueAt(selectedRow, 0).toString());
   
        Req_EmergencyDir reqEmergencyDir =system.getEmergencyReqDir();
        ArrayList<Req_Emergency> emergencies = reqEmergencyDir.getEmergencyUserList();
        int size = emergencies.size();
        for(int i=0;i<size;i++)
        {
            Req_Emergency emergency = emergencies.get(i);
            if(rowId == emergency.getId()/*&&o.getStatus().matches("Deliver Man Assigned")*/)
            {
                if(emergency.getStatus().matches("Closed"))
                {
                    JOptionPane.showMessageDialog(null, "Emergency Closed");
                }
                else if(emergency.getStatus().matches("False Alaram"))
                {
                    JOptionPane.showMessageDialog(null, "Emergency is a false Alaram");
                }
                else if(emergency.getResponse().matches("No Response"))
                {
                    JOptionPane.showMessageDialog(null, "respond to emergency");
                }
                else
                {
                    emergency.setStatus("Closed");
                }

            }

        }
        jTable1.setModel(new DefaultTableModel(null,new String[]{"ID","Name","Emergency","Location","Status","Response"}));
        populate_table();
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Select A Row!!");
        }
    }//GEN-LAST:event_closeCaseActionPerformed

    private void respondButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_respondButtonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel  table = (DefaultTableModel) jTable1.getModel();
        int selectedRow=jTable1.getSelectedRow();
        if(selectedRow>=0)
        {       
        int rowId = Integer.parseInt(table.getValueAt(selectedRow, 0).toString());
        
        Req_EmergencyDir reqEmergencyDir = system.getEmergencyReqDir();
        ArrayList<Req_Emergency> emergencies = reqEmergencyDir.getEmergencyUserList();
        int u = emergencies.size();
        Fire a=(Fire)userAcc;
        for(int i=0;i<u;i++)
        {
            Req_Emergency emergency = emergencies.get(i);
            if(rowId == emergency.getId()/*&&o.getStatus().matches("Deliver Man Assigned")*/)
            {
                if(emergency.getStatus().matches("Closed"))
                {
                    JOptionPane.showMessageDialog(null, "Emergency Closed");
                }
                else if(emergency.getStatus().matches("False Alaram"))
                {
                    JOptionPane.showMessageDialog(null, "Emergency is a false Alaram");
                }
                else if(emergency.getResponse().matches("No Response"))
                {
                    emergency.setResponse(a.getNameFireman()+" "+"Responded");
                }
                else
                {
                   JOptionPane.showMessageDialog(null, "Already Responded!!"); 
                }
                

            }

        }
        jTable1.setModel(new DefaultTableModel(null,new String[]{"ID","Name","Emergency","Location","Status","Response"}));
        populate_table();
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Select A Row!!");
        }
    }//GEN-LAST:event_respondButtonActionPerformed

    private void locationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locationButtonActionPerformed
        // TODO add your handling code here:
        showMap();

    }//GEN-LAST:event_locationButtonActionPerformed

    private void showMap() {
          DefaultTableModel  table2 = (DefaultTableModel) jTable1.getModel();
        int selectedRow=jTable1.getSelectedRow();
        if(selectedRow>=0)
        {       
        int rowId = Integer.parseInt(table2.getValueAt(selectedRow, 0).toString());
        Req_EmergencyDir reqEmergencyDirectory=system.getEmergencyReqDir();
        ArrayList<Req_Emergency> reqEmergencyList = reqEmergencyDirectory.getEmergencyUserList();
        int size= reqEmergencyList.size();
        Fire police =(Fire) userAcc;
        for(int i=0;i<size;i++)
        {
            Req_Emergency emergency = reqEmergencyList.get(i);
            if(rowId ==emergency.getId())
            {
                locationCordinate = emergency.getLocation();
            }

        }
        String [] parts = locationCordinate.split(",");
        String lattitude = parts[0].replaceAll("\\s","");
        String longitude = parts[1].replaceAll("\\s","");
        
        MapViewerTwo oLJP = new MapViewerTwo(container, lattitude, longitude);
        container.add("MapViewr", oLJP);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Select A Row!!");
        }
        
        
        
//        String [] parts = locationCordinate.split(",");
//        String lattitude = parts[0].replaceAll("\\s","");
//        String longitude = parts[1].replaceAll("\\s","");
//        
//        MapViewerTwo oLJP = new MapViewerTwo(container, lattitude, longitude);
//        container.add("MapViewr", oLJP);
//        CardLayout layout = (CardLayout) container.getLayout();
//        layout.next(container);
    }
    
     public void populate_table()
    {
        Req_EmergencyDir reqEmergencyDir = system.getEmergencyReqDir();
        ArrayList<Req_Emergency> emergencies = reqEmergencyDir.getEmergencyUserList();
        int size = emergencies.size();
        
        for(int i=0;i<size;i++)
        {
            Req_Emergency emergency = emergencies.get(i);
            if(emergency.getEmergency().matches("Fire"))
            {
            
                DefaultTableModel table = (DefaultTableModel) jTable1.getModel();
                String s1=String.valueOf(emergency.getId());
                
                
                String s[]={s1,emergency.getName(),emergency.getEmergency(),emergency.getLocation(),emergency.getStatus(),emergency.getResponse()};
                table.addRow(s);
            
            }
            
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeCase;
    private javax.swing.JButton falseAlarm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton locationButton;
    private javax.swing.JButton respondButton;
    // End of variables declaration//GEN-END:variables
}
